add paypal code block
redbrick/hexo-theme-icarus pull request #45
Opened 2017-04-26 20:49 UTC by butlerx

adds the ability to call `{% paypal %}` and insert a paypal joining form to anypage

2017-04-26 22:50 UTC, VoyTechnology commented
Didn't look at PayPal API in a while but iirc there is a way to call the sandbox server. I think the URL should depend on whether the page is running in prod (`PROD=true` Env var?)

2017-04-26 22:53 UTC, VoyTechnology commented on layout/paypal.ejs
> +        Student
This probably doesn't impact the style of if but I think this should be encapsulated in `<label>`

2017-04-26 22:53 UTC, VoyTechnology commented on layout/paypal.ejs
> +        Associate or Staff
Consider `<label>`

2017-04-26 22:53 UTC, VoyTechnology commented on layout/paypal.ejs
> +        Associate(Including Donation)
Consider `<label>`

2017-04-27 08:25 UTC, butlerx commented
we cant differentiate on the static files if they are production or not

2017-04-28 19:40 UTC, VoyTechnology requested changes

2017-04-28 19:40 UTC, VoyTechnology commented on layout/paypal.ejs
> +<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="paypal">
I would like to approve this, and everything else LGTM, but honestly the sandbox functionality is a deal breaker for me. Can't we not pass in a param saying the code is in debug mode?

2017-04-28 19:44 UTC, butlerx commented on layout/paypal.ejs
> +<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="paypal">
1. hexo doesnt do anything like that for site generation
2. why do we even need it its just a form, there's no user flow to test. You click paypal a tab is opened and you stop.

2017-04-28 20:15 UTC, VoyTechnology approved these changes

2017-04-28 20:15 UTC, VoyTechnology commented on layout/paypal.ejs
> +<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="paypal">
Ok, but I think in the future if we add ability to automagically renew, we should also make sure the flow works and add the sandbox.

2017-04-28 20:16 UTC, merged